# -*- coding: utf-8 -*-
"""Projeto_ML.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m4003BIvQkFDuVH-RpJsuE0aXX6R1Kr2
"""

#importando bibliotecas
import requests
import pandas as pd
from bs4 import BeautifulSoup

entrada = input("Digite o que deseja buscar: ")
pesquisa = entrada.strip().replace(" ", "-")

if pesquisa.startswith("-"):  # verificando se a string começa com hífen
    pesquisa = pesquisa[1:]  # remover o primeiro caractere hífen

if pesquisa.endswith("-"):  # verificando se a string termina com hífen
    pesquisa = pesquisa[:-1]  # remover o último caractere hífen

#criando variável para o link
link = "https://lista.mercadolivre.com.br/" + pesquisa
print(link)

#testando a comunicação com o site
comunicacao = requests.get(link)
#print(comunicacao)

#pegando informações no site
site = BeautifulSoup(comunicacao.text, "html.parser")

#buscando os dados específicos
dados = site.find_all("div", attrs = {"class": "ui-search-result__content-wrapper shops__result-content-wrapper"})

produtos = []
precos = []
links = []

for x in dados:
  nome_produto = x.find_all("h2")[0].text
  produtos.append(nome_produto)
  preco_produto = x.find_all("span", class_ = "price-tag-amount")[0].text
  preco_produto2 = float(preco_produto.replace("R$","").replace(".","").replace(",","."))
  precos.append(preco_produto2)
  link_produto = x.find_all("a", class_ = "ui-search-link")[0]['href']
  links.append(link_produto)

#transformando em tabela
tabela = {
    "Nome" : produtos,
    "Preço" : precos,
    "Link" : links
}

tabela = pd.DataFrame(tabela)
tabela_ordenada = tabela.sort_values(by="Preço")

for index, row in tabela_ordenada.iterrows():
    print(row['Nome'], "/", row['Preço'])
    print(row['Link'])
    print()